parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     SiegeCraft
    database_user:     root
    database_password: bigoti

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            d3447b2a10d5aac75a46c5e10db28dd74c