ts_user:
    resource: "@TSUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}

game_config:
    resource: "@TSGameConfigBundle/Controller/"
    type:     annotation
    prefix:   /admin/config/

siege_craft:
    resource: "@TSSiegeCraftBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}

root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%
        permanent: true